### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by Zazama** [aaroniker/framy-css#1]
I checked the css file for browser support, it should be like this:

```
Webkit      IE      Firefox     Edge

21          11      18          12
```

Mostly due to the flex grid.
I couldn't test IE10 though. IE11 displays everything correct. IE10 doesn't support all flex box properties used.
It might be possible to support IE9 and 10 if one includes https://github.com/jonathantneal/flexibility

**Comment by aaroniker** [comment]
Thanks a lot!
IE 10 should work too, because of the -ms- prefix (Tested this with dev tools).

I'll think about a fallback float grid for IE <= 9 (would be available with the customize editor)

**Comment by Zazama** [comment]
flex-grow isn't supported though, not sure if it makes any difference or problems. Flex support/behaviour isn't the best in IE10, that's why I'm a bit sceptical :laughing:
