### ISSUE TITLE
Option that controls the import of fonts

### ISSUE THREAD

**Issue by JoshuaBehrens** [aaroniker/framy-css#10]
I was looking for a minimal framework to use with [AMP](//ampproject.org/). There you are forced to use special font vendors. I discarded this framework for not being able to easily disable font import by configuration or set the vendor/cdn path. I'd like to see one if this for future projects on my behalf but have to skip you for now. I'd like to use this framework also for AMP projects.

**Comment by aaroniker** [comment]
Hi, thanks for your feedback!
Currently im working on an easy customizer integration on the website :)
Should be finished the next days / week.

Else you can go into the `src/scss/vars.scss` and edit the variables to your need - dont forget to recompile css.

thanks!

**Comment by JoshuaBehrens** [comment]
I know I can edit it there. I prefer a submodule solution that is fully configurable by variables. Thous the issue. I could implement it too if you are open for pull requests.

**Comment by aaroniker** [comment]
@JoshuaBehrens ofc i'm always open for help / pr's :)
would be great! thanks a lot - currently im really busy with the new website

**Comment by JoshuaBehrens** [comment]
Solved with #11 on my behalf.
