### ISSUE TITLE
Keep Old Demo

### ISSUE THREAD

**Issue by ayushsharma82** [aaroniker/framy-css#12]
Please reupload old demo page until new demo is finished. It is very difficult for a developer to pick a framework without knowing all components.

**Comment by aaroniker** [comment]
hi @ayushsharma82 
all components should be at the /demo directory - or are u missing something? :)
Pls tell me, i will update it then!

**Comment by ayushsharma82** [comment]
@aaroniker My Suggestion is to Host that Old Demo page at demo.framycss.org until new demo page is finished.

**Comment by aaroniker** [comment]
@ayushsharma82 

like this? http://demo.framycss.org :)

**Comment by ayushsharma82** [comment]
Great :) Thanks. It will surely help others too.
