### ISSUE TITLE
white-space: pre;

### ISSUE THREAD

**Issue by chriskonnertz** [aaroniker/framy-css#13]
Hello,

why do you use instead of "white-space: pre;" on pre-elements? It seems to be a bug:

```
white-space: pre;
white-space: pre-wrap;
white-space: pre-line;
```

This is what Chromium display as the current styling for pre-elements.

**Comment by aaroniker** [comment]
Hi,

good point - cant remember tbh :D 
I think i'll just remove these 3 lines, not necessary

Thanks! I'll update that :)

**Comment by chriskonnertz** [comment]
Great, thanks!

**Comment by aaroniker** [comment]
https://github.com/aaroniker/framy-css/commit/614ff12b78b812dd8598c7844270f5cfe866e014 

fyi @chriskonnertz - also improved some other things :)

**Comment by chriskonnertz** [comment]
Thank you!
