### ISSUE TITLE
Customize editor

### ISSUE THREAD

**Issue by aaroniker** [aaroniker/framy-css#2]
Some planned features (partially finished):

- Switch between simple/advanced editor view
- Set all SCSS variables
  - Colors
  - Typo (font-family, line-height, ...)
  - Spacing
  - ...
- Select components
- Format (minified, ...)
- Download generated css file

**Comment by aaroniker** [comment]
- config.json to import / export settings (later)

**Comment by JoshuaBehrens** [comment]
Is #10 a part of this?

**Comment by aaroniker** [comment]
@JoshuaBehrens yep, also working on your issue :)
