### ISSUE TITLE
Components

### ISSUE THREAD

**Issue by aaroniker** [aaroniker/framy-css#3]
List of finished / planned components:
- [x] Flexbox Grid
- [x] Buttons (+ Icons)
- [x] Icons (Ionicons integrated)
- [x] Typography (Roboto used)
- [x] Lists
- [x] Forms (WIP)
- [x] Tables (WIP)
- [x] CSS Helper classes (more to add)

**Comment by aaroniker** [comment]
- [x] Button Groups

**Comment by jhvh** [comment]
Hey man, this css framework looks dope!

Any chance you will add more components like menu, cards, etc?

**Comment by aaroniker** [comment]
@jhvh hi, of course!
just suggest some here which you would like to see :)

i'll work on the customize editor next

**Comment by jhvh** [comment]
I would love to see a menu/navigation component. I think that's the main component I'm missing right now. Other than that this really looks damn clean, I can see this grow very big (like Semantic-UI) if more components are added. I will keep an eye on this repo. :+1:

**Comment by aaroniker** [comment]
thanks!
i'll take a look on a menu/nav component - but i wont make this too heavy - i'll finish the customize editor first (choose own colors/components etc): #2

**Comment by aaroniker** [comment]
- [ ] Menu
- [ ] Breadcrumb
- [ ] Card
- [ ] Tabs / Accordion (no JS)

**Comment by jhvh** [comment]
Awesome!

If you want I can PR for some example pages. I think it would be nice to offer some example pages (login, etc) for people to get started.

**Comment by aaroniker** [comment]
Would be cool :)

**Comment by FarhanShares** [comment]
keep the menu simple yet unique and stylish

**Comment by aaroniker** [comment]
working on more complicated & individual components later on ...
